# Generated by Django 2.2 on 2020-08-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='наименование категории')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование')),
                ('image', models.ImageField(blank=True, upload_to='prodacts_photo', verbose_name='Фото товара')),
                ('short_descr', models.CharField(blank=True, max_length=64, verbose_name='краткое описание товара')),
                ('description', models.TextField(blank=True, verbose_name='описание товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CategoryProduct', verbose_name='категория товара')),
            ],
        ),
    ]
