# Generated by Django 2.2 on 2020-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_descr',
            field=models.CharField(blank=True, default='{% static "img/logo.png" %}', max_length=64, verbose_name='краткое описание товара'),
        ),
    ]
