# Generated by Django 2.2 on 2020-08-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200829_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/prod/logo.png', upload_to='prodacts_photo', verbose_name='Фото товара'),
        ),
    ]
