# Generated by Django 2.2 on 2020-09-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200905_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
