# Generated by Django 2.2 on 2020-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='prodacts_photo/logo.png', upload_to='prodacts_photo'),
        ),
    ]
