# Generated by Django 2.2 on 2020-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='age',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='возраст'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='photouser',
            field=models.ImageField(blank=True, default='user_photo/logo.png', upload_to='user_photo', verbose_name='Фото пользователя'),
        ),
    ]
