# Generated by Django 2.2 on 2020-08-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200829_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='photouser',
            new_name='userphoto',
        ),
    ]
