# Generated by Django 2.2 on 2020-08-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200830_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='userphoto',
            new_name='photo',
        ),
    ]
